# author is used in the atom feed
title: Red Hat JBoss Developer Program
author: Ray Ploski
description: Some witty description

profiles:
  development:
    base_url: http://localhost:4242
  production:
    base_url: http://devprogram-jbossdeveloper.rhcloud.com
